import { ServiceAnswers } from "@/components/ServiceAnswers";
import { services } from "@/content/services";
import { JsonLd } from "@/components/JsonLd";
import { site } from "@/lib/site";
import { PageHeader,Section,Container,SectionHeading,CTASection } from "@/components/UI";
import { pageMeta } from "@/lib/metadata";
export const metadata=pageMeta("Microsoft AI Governance","Connect Microsoft AI deployment with identity, data protection, environment controls, and operating responsibilities.","/microsoft-ai");
const references=[["Microsoft Entra Agent ID","https://learn.microsoft.com/en-us/entra/agent-id/"],["Copilot Studio security and governance","https://learn.microsoft.com/en-us/microsoft-copilot-studio/security-and-governance"],["Microsoft Purview and Copilot Studio","https://learn.microsoft.com/en-us/purview/ai-copilot-studio"],["Microsoft Foundry agent identity","https://learn.microsoft.com/en-us/azure/foundry/agents/concepts/agent-identity"]];
export default function Page(){return <><PageHeader label="Microsoft AI" title="A connected stack needs connected governance." text="Microsoft AI is an important specialization. We examine identity, data, agents, environments, and integrations as one operating architecture." path="/microsoft-ai"/><Section><Container><SectionHeading label="Technical focus" title="Start with the workload and its control boundaries."/><div className="technology-grid microsoft-grid">{[["Microsoft 365 Copilot","Review rollout readiness and access to grounding sources."],["Copilot Studio","Review agent actions, connectors, environment controls, and operating ownership."],["Microsoft Entra","Examine identity, authorization, access reviews, and agent lifecycle requirements."],["Microsoft Purview","Map relevant data protection and audit capabilities to the workload."],["Microsoft Foundry","Review model and agent architecture, resource access, and integration boundaries."],["Agent 365","Evaluate agent inventory and governance integration for the selected deployment."],["Power Platform","Review environments, connectors, approvals, and workflow responsibilities."],["SharePoint + Microsoft Graph","Review source permissions and the paths through which applications reach data."]].map(([t,d])=><article key={t}><h3>{t}</h3><p>{d}</p></article>)}</div><div className="callout"><strong>Capabilities depend on the actual environment.</strong><p>Licensing, product availability, configuration, and deployment model affect which controls apply. No single product automatically makes an AI system compliant or fully governed.</p></div><div className="sources"><h2>Official technical references</h2><p>Terminology reviewed October 7, 2026. Validate applicability during an engagement.</p><ul>{references.map(([t,h])=><li key={h}><a href={h} target="_blank" rel="noopener noreferrer">{t}<span className="sr-only"> (opens in a new tab)</span></a></li>)}</ul></div><ServiceAnswers service={services.find(s=>s.slug==="microsoft-ai-governance")!}/></Container></Section><JsonLd data={{"@context":"https://schema.org","@type":"Service","@id":site.url+"/microsoft-ai#service",name:"Microsoft AI Governance",serviceType:"Microsoft AI Governance",description:services.find(s=>s.slug==="microsoft-ai-governance")!.summary,url:site.url+"/microsoft-ai",provider:{"@id":site.url+"/#organization"}}}/><CTASection/></>;}
