"use client";
import {useId,useState} from "react";
import {Fingerprint,ShieldCheck,Database,FileCheck2,Workflow,ArrowRight} from "lucide-react";
const controls=[
 {icon:Fingerprint,title:"Agent identity",detail:"A defined owner and purpose",question:"Who is acting, and on whose authority?",decision:"Distinguish delegated user access from an application or agent identity. Assign an accountable owner and a retirement path.",failure:"An owner leaves, but the agent keeps its access.",evidence:"Identity inventory, owner record, and revocation test."},
 {icon:ShieldCheck,title:"Authorization",detail:"Only the actions approved",question:"What can the agent actually do?",decision:"Define allowed actions per resource. Separate reading from writing, and require approval for consequential changes.",failure:"A read-only use case inherits broad write permissions.",evidence:"Permission map, approval gates, and denied-action tests."},
 {icon:Database,title:"Tools + data",detail:"An explicit resource boundary",question:"Which systems can it reach?",decision:"Use deliberate interfaces that enforce source permissions, input validation, and business rules. Review each new connector.",failure:"A connector bypasses the rules enforced by the application.",evidence:"Tool inventory, data boundary, and integration tests."},
 {icon:FileCheck2,title:"Evidence",detail:"A record of what happened",question:"Can the action be explained afterward?",decision:"Record the action, authority, outcome, and applicable approval. Establish access and retention responsibilities.",failure:"Logs show activity without explaining who authorized it.",evidence:"Traceable action records and an operating review process."}
];
export function ArchitectureExplorer({compact=false}:{compact?:boolean}){const [active,setActive]=useState(0);const id=useId();return <figure className={"architecture-board interactive-board "+(compact?"board-compact":"")}><figcaption><span className="signal-dot"/>CONTROL BY DESIGN<span className="board-ref" aria-hidden="true">AS / 01</span></figcaption><div className="board-intent"><span>BUSINESS INTENT</span><p>A useful agent.<br/>A deliberate boundary.</p><Workflow size={24} aria-hidden="true"/></div><p className="explorer-hint">Select a layer to explore the control.</p><ol className="architecture-nodes">{controls.map(({icon:Icon,title,detail},i)=><li key={title} className={active===i?"node-selected":""}><button type="button" id={id+"-trigger-"+i} aria-expanded={active===i} aria-controls={id+"-panel-"+i} onClick={()=>setActive(i)}><span className="node-icon"><Icon size={20} aria-hidden="true"/></span><span className="node-copy"><span className="node-index">0{i+1}</span><strong>{title}</strong><span className="node-description">{detail}</span></span><ArrowRight size={15} aria-hidden="true"/></button></li>)}</ol><div className="control-panels">{controls.map((c,i)=><section key={c.title} id={id+"-panel-"+i} aria-labelledby={id+"-trigger-"+i} hidden={active!==i}><h3>{c.question}</h3><p>{c.decision}</p><dl><div><dt>Failure to prevent</dt><dd>{c.failure}</dd></div><div><dt>Evidence to retain</dt><dd>{c.evidence}</dd></div></dl></section>)}</div><div className="board-caption"><span className="signal-dot"/><span>Explore the boundary. Then test it.</span></div></figure>;}
