"use client";
import Link from "next/link";
import { BrandMark } from "./BrandMark";
import { MenuIllustration } from "./MenuIllustration";
import { usePathname } from "next/navigation";
import * as Dialog from "@radix-ui/react-dialog";
import { Menu, X, ArrowUpRight, ChevronDown } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { nav } from "@/lib/site";
import { services, serviceHref } from "@/content/services";
const panels = nav.map((item,index) => ({...item,links:index===0 ? services.map(s=>({label:s.title,href:serviceHref(s),description:s.summary})) : [{label:item.label,href:item.href,description:["","Identity, authorization, data boundaries, and evidence for enterprise agents.","Microsoft AI implementation with enterprise controls and operating responsibilities.","From current-state review to implementation and operational handover.","Practical perspectives on enterprise AI engineering and governance."][index]}, ...(index===1 ? [{label:"Governance assessment",href:"/services/ai-governance-assessment",description:"Examine deployed AI and identify gaps in technical controls."}] : index===2 ? [{label:"Explore all services",href:"/services",description:"Architecture, integration, security, and ongoing operations."}] : index===3 ? [{label:"About AdaptSphere",href:"/about",description:"Our approach to governed AI engineering."},{label:"Start a conversation",href:"/contact",description:"Discuss your environment and the work ahead."}] : [])]}));
export function Wordmark(){return <Link href="/" aria-label="AdaptSphere home" className="wordmark"><BrandMark/><span>AdaptSphere<sup className="brand-trademark" aria-hidden="true">™</sup><span className="wordmark-sub">GOVERNED AI ENGINEERING</span></span></Link>;}
export function SiteHeader(){
 const [open,setOpen]=useState(false),[active,setActive]=useState<number|null>(null); const path=usePathname();
 const header=useRef<HTMLElement>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),triggers=useRef<(HTMLButtonElement|null)[]>([]);
 const cancel=()=>{if(timer.current)clearTimeout(timer.current);};
 useEffect(()=>{const dismiss=(e:PointerEvent)=>{if(!header.current?.contains(e.target as Node))setActive(null);};const resize=()=>setActive(null);document.addEventListener("pointerdown",dismiss);window.addEventListener("resize",resize);return()=>{document.removeEventListener("pointerdown",dismiss);window.removeEventListener("resize",resize);if(timer.current)clearTimeout(timer.current);};},[]);
 return <header ref={header} className="site-header" onPointerEnter={cancel} onPointerLeave={()=>{cancel();timer.current=setTimeout(()=>setActive(null),180);}} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget)){cancel();setActive(null);}}} onKeyDown={e=>{if(e.key==="Escape"&&active!==null){triggers.current[active]?.focus();setActive(null);}}}>
 <div className="container header-row"><Wordmark/><nav className="desktop-nav" aria-label="Primary">{panels.map((n,i)=><button ref={el=>{triggers.current[i]=el;}} className={"nav-trigger nav-item nav-item-"+i} key={n.href} aria-expanded={active===i} aria-controls={"nav-panel-"+i} onPointerEnter={e=>{if(e.pointerType==="mouse"){cancel();setActive(i);}}} onClick={()=>{cancel();setActive(active===i?null:i);}} onKeyDown={e=>{if(e.key==="ArrowDown"){e.preventDefault();setActive(i);requestAnimationFrame(()=>document.getElementById("nav-panel-"+i)?.querySelector<HTMLAnchorElement>("a")?.focus());}}}>{n.label}<ChevronDown size={11} aria-hidden="true"/></button>)}</nav><Link className="header-contact" href="/contact" onFocus={()=>setActive(null)}>Let’s talk<ArrowUpRight size={15} aria-hidden="true"/></Link>
 <Dialog.Root open={open} onOpenChange={value=>{setOpen(value);setActive(null);}}><Dialog.Trigger className="menu-button"><span className="more-label">More</span><ChevronDown className="more-chevron" size={15} aria-hidden="true"/><Menu className="hamburger-icon" aria-hidden="true"/><span className="mobile-menu-label sr-only">Open menu</span></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="menu-overlay"/><Dialog.Content className="mobile-sheet"><Dialog.Title className="sr-only">Site navigation</Dialog.Title><Dialog.Description className="sr-only">Explore AdaptSphere services and contact details.</Dialog.Description><Wordmark/><Dialog.Close className="menu-close" aria-label="Close menu"><X aria-hidden="true"/></Dialog.Close><nav className="overflow-nav" aria-label="Site">{[...nav,{label:"About",href:"/about"},{label:"Contact",href:"/contact"}].map((n,i)=><Link className={i<nav.length?"nav-item nav-item-"+i:undefined} key={n.href} href={n.href} onClick={()=>setOpen(false)} aria-current={path.startsWith(n.href)?"page":undefined}>{n.label}</Link>)}</nav><p>Architecture. Engineering. Governance.</p></Dialog.Content></Dialog.Portal></Dialog.Root></div>
 {panels.map((n,i)=><section key={n.href} id={"nav-panel-"+i} aria-label={n.label+" submenu"} className="mega-panel" hidden={active!==i}><div className="container"><div className="mega-heading"><div><p className="eyebrow">Explore AdaptSphere</p><h2>{n.label}</h2></div><Link href={n.href} onClick={()=>setActive(null)} className="mega-overview">View {n.label.toLowerCase()}<ArrowUpRight size={16} aria-hidden="true"/></Link></div><ul className="mega-grid">{n.links.map(link=><li key={link.href}><Link href={link.href} onClick={()=>setActive(null)} aria-current={path===link.href?"page":undefined}><span className="mega-icon"><MenuIllustration href={link.href}/></span><span><strong>{link.label}</strong><span className="mega-description">{link.description}</span></span><ArrowUpRight className="mega-arrow" size={15} aria-hidden="true"/></Link></li>)}</ul></div></section>)}
 </header>;
}


