import { WorkflowScene } from "@/components/WorkflowScene";
import { DeliveryExplorer } from "@/components/DeliveryExplorer";
import { EngagementFinder } from "@/components/EngagementFinder";
import { Container,Section,Eyebrow,ButtonLink,SectionHeading,TextLink,CTASection } from "@/components/UI";
import { ModernizationFlow } from "@/components/Diagrams";
import { InsightCard } from "@/components/Cards";
import { ServiceExplorer } from "@/components/ServiceExplorer";
import { insights } from "@/content/insights";
import { pageMeta } from "@/lib/metadata";
export const metadata=pageMeta("Enterprise AI Implementation & Governance","AdaptSphere reviews your workflows and systems, identifies useful AI opportunities, and builds governed AI integrations. Microsoft is our main specialization.","/");
export default function Home(){return <>
<section className="home-hero"><Container><div className="hero-grid"><div className="hero-copy"><Eyebrow>Governed AI implementation</Eyebrow><h1>Make your existing systems <em>work better with AI.</em></h1><p>We review your workflows, applications, and data to find where AI can reduce manual work and help people make decisions. Then we build and integrate the solution with defined access, approvals, and ownership.</p><div className="actions"><ButtonLink href="/contact">Discuss Your Workflow</ButtonLink><ButtonLink href="/how-we-work" secondary>See How We Work</ButtonLink></div><p className="hero-footnote">Forward-deployed engineering, with governance built in.</p></div><DeliveryExplorer/></div><div className="hero-baseline"><span>REVIEW YOUR SYSTEMS</span><span>IDENTIFY AI OPPORTUNITIES</span><span>BUILD + VERIFY</span><p>Microsoft expertise. Broader AI capability.</p></div></Container></section>
<Section className="visual-use-cases"><Container><div className="split-intro"><SectionHeading label="Where AI can help" title="Start with the work your team does every day."/><p className="large-copy">Identify repetitive tasks, hard-to-find information, and disconnected applications. Evaluate where AI fits before choosing a tool.</p></div><div className="problem-grid">{[["01","Reduce repetitive work","Assess document processing, reporting, and follow-up tasks for automation. Keep human approval where a decision or change needs review."],["02","Find useful information","Build search and assistants around company knowledge. Respect source permissions so staff can access the information they are authorized to use."],["03","Connect existing applications","Integrate AI with business systems through controlled interfaces. Define what it can read or change, and test how it handles failures."]].map(([n,t,d])=><article key={n}><div className="use-case-art"><WorkflowScene variant={Number(n)-1}/></div><span className="card-number">{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></Container></Section>
<Section className="dark-band"><Container><div className="manifesto"><Eyebrow>Governed AI Engineering</Eyebrow><h2>Governance belongs<br/>in the <em>architecture.</em></h2><p>We connect architecture, implementation, and governance. The result is a defined path from business intent to working systems, with controls and operating responsibilities built in.</p><TextLink href="/services/governed-ai-architecture">Explore AI architecture and implementation</TextLink></div><div className="control-list control-disclosures">{[["Identity + authorization","Give each agent an identity. Define which tools it can use, whose authority it acts under, and where approval is required."],["Security + data boundaries","Limit access to the data and systems needed for the task. Review permissions, sensitive information, and integration boundaries."],["Ownership + lifecycle","Name the people responsible for deployment, access reviews, changes, and retirement. Make ownership part of the operating model."],["Evidence + review","Record relevant actions and approvals so the team can investigate failures, review decisions, and verify controls."]].map(([title,description],i)=><details key={title} name="home-controls"><summary><span>0{i+1}</span>{title}<span className="control-toggle" aria-hidden="true">+</span></summary><p>{description}</p></details>)}</div></Container></Section>
<Section id="engagements"><Container><div className="section-heading-row"><SectionHeading label="Core engagements" title="AI assessment, implementation, and remediation." text="Review an existing deployment, design a new agent, or implement the controls identified in an assessment."/><TextLink href="/services">All services</TextLink></div><p className="explorer-instruction">Choose an engagement to see the work and deliverables. Hover, tap, or use the arrow keys.</p><ServiceExplorer/></Container></Section>
<EngagementFinder/>
<Section className="muted-section"><Container><div className="feature-grid"><div><Eyebrow>Agent governance + authorization</Eyebrow><h2>Every agent needs<br/>a defined authority.</h2><p>Set the owner, identity, permitted actions, resource boundaries, and review gates before expanding autonomy.</p><TextLink href="/agent-governance">See the authorization path</TextLink></div><div className="control-questions">{["Who owns this agent?","Which identity does it use?","What can it read or change?","What requires approval?","How is access reviewed and retired?"].map((q,i)=><p key={q}><span>0{i+1}</span>{q}</p>)}</div></div></Container></Section>
<Section><Container><div className="feature-grid"><div><Eyebrow>Microsoft AI specialization</Eyebrow><h2>Deploy Microsoft AI.<br/>Define who can access what.</h2><p>Prepare Microsoft 365 Copilot and Copilot Studio deployments by reviewing source permissions, agent actions, and environment controls. Connect Entra identity and Purview data protection to the workload in scope.</p><TextLink href="/microsoft-ai">Microsoft AI Governance</TextLink></div><div className="technology-grid">{[["Microsoft 365 Copilot","Source access + deployment readiness"],["Copilot Studio","Agents + environment controls"],["Microsoft Entra","Identity + authorization"],["Microsoft Purview","Data protection + evidence"],["Microsoft Foundry","Model + agent architecture"],["Power Platform","Workflow + integration boundaries"]].map(([t,d])=><div key={t}><strong>{t}</strong><p>{d}</p></div>)}</div></div></Container></Section>
<Section className="muted-section"><Container><div className="feature-grid"><div><Eyebrow>Integration + modernization</Eyebrow><h2>Connect AI to your<br/>existing applications.</h2><p>Connect agents to legacy applications through APIs and controlled data access. Define permissions, approval steps, and failure handling before allowing an agent to read or change business records.</p><TextLink href="/services/ai-integration-modernization">Explore modernization</TextLink></div><ModernizationFlow/></div></Container></Section>
<Section><Container><SectionHeading label="How we work" title="Close to your systems. Clear about the next step."/><ol className="process-grid">{[["Understand","Map systems, data, identities, constraints, and purpose."],["Design","Define architecture, permissions, boundaries, and ownership."],["Implement","Build the integrations and controls in an agreed scope."],["Operate","Verify behavior, hand over evidence, and establish reviews."]].map(([t,d],i)=><li key={t}><span className="card-number">0{i+1}</span><h3>{t}</h3><p>{d}</p></li>)}</ol><TextLink href="/how-we-work">Our delivery approach</TextLink></Container></Section>
<Section className="platform-section"><Container><div className="section-heading-row"><SectionHeading label="Engineering in practice" title="Close to the realities of production." text="Selected platform engineering and technical operations on independent digital properties."/><TextLink href="/services/platform-engineering">Platform engineering</TextLink></div><div className="platform-grid"><article><span className="eyebrow">Research platform</span><h3>sougataroy.com<span className="sr-only">Independent research property</span></h3><p>Next.js development, content infrastructure, hosting and domain administration, deployment, and ongoing technical operations.</p></article><article><span className="eyebrow">Digital media + resources</span><h3>Voyagers Beyond</h3><p>Platform engineering, content infrastructure, deployment, maintenance, and automation.</p></article></div><p className="small-note">Content and editorial rights remain with the respective property owners. These references describe technical work, not paid-client or endorsement claims.</p></Container></Section>
<Section><Container><div className="section-heading-row"><SectionHeading label="Insights" title="The decisions beneath the technology."/><TextLink href="/insights">All insights</TextLink></div><div className="insight-grid">{insights.map(item=><InsightCard key={item.slug} item={item}/>)}</div></Container></Section><CTASection/></>;}
