import { EngagementFinder } from "@/components/EngagementFinder";
import { Container,Section,Eyebrow,ButtonLink,SectionHeading,TextLink,CTASection } from "@/components/UI";
import { ArchitectureDiagram,ModernizationFlow } from "@/components/Diagrams";
import { InsightCard } from "@/components/Cards";
import { ServiceExplorer } from "@/components/ServiceExplorer";
import { insights } from "@/content/insights";
import { pageMeta } from "@/lib/metadata";
export const metadata=pageMeta("Enterprise AI Implementation & Governance","AI implementation, agent governance, Microsoft Copilot readiness, and legacy integration. AdaptSphere connects enterprise AI to your systems with defined access controls.","/");
export default function Home(){return <>
<section className="home-hero"><Container><div className="hero-grid"><div className="hero-copy"><Eyebrow>Enterprise AI architecture + governance</Eyebrow><h1>Build AI you can<br className="desktop-break"/> actually <em>control.</em></h1><p>AdaptSphere helps IT and security teams implement enterprise AI, govern agents, and connect existing applications. Define what AI can access, which actions need approval, and who owns it after launch.</p><div className="actions"><ButtonLink href="/contact">Assess Your AI Environment</ButtonLink><ButtonLink href="/how-we-work" secondary>How We Work</ButtonLink></div><p className="hero-footnote">Built around your systems. Governed from the start.</p></div><ArchitectureDiagram/></div><div className="hero-baseline"><span>ARCHITECTURE</span><span>ENGINEERING</span><span>GOVERNANCE</span><p>One connected discipline.</p></div></Container></section>
<Section><Container><div className="split-intro"><SectionHeading label="The gap beneath AI" title="A working demo is not an operating model."/><p className="large-copy">AI connects to real systems. The decisions around it need to be just as real.</p></div><div className="problem-grid">{[["01","Access without a boundary","An agent can act. But who decided what it should be allowed to do?"],["02","Policy without implementation","A governance document exists. But which identities, permissions, and data controls enforce it?"],["03","Deployment without ownership","A system goes live. But who reviews its access, approves changes, and retires it?"]].map(([n,t,d])=><article key={n}><span className="card-number">{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></Container></Section>
<Section className="dark-band"><Container><div className="manifesto"><Eyebrow>Governed AI Engineering</Eyebrow><h2>Governance belongs<br/>in the <em>architecture.</em></h2><p>We connect architecture, implementation, and governance. The result is a defined path from business intent to working systems, with controls and operating responsibilities built in.</p><TextLink href="/services/governed-ai-architecture">Explore AI architecture and implementation</TextLink></div><div className="control-list control-disclosures">{[["Identity + authorization","Give each agent an identity. Define which tools it can use, whose authority it acts under, and where approval is required."],["Security + data boundaries","Limit access to the data and systems needed for the task. Review permissions, sensitive information, and integration boundaries."],["Ownership + lifecycle","Name the people responsible for deployment, access reviews, changes, and retirement. Make ownership part of the operating model."],["Evidence + review","Record relevant actions and approvals so the team can investigate failures, review decisions, and verify controls."]].map(([title,description],i)=><details key={title} name="home-controls"><summary><span>0{i+1}</span>{title}<span className="control-toggle" aria-hidden="true">+</span></summary><p>{description}</p></details>)}</div></Container></Section>
<Section id="engagements"><Container><div className="section-heading-row"><SectionHeading label="Core engagements" title="AI assessment, implementation, and remediation." text="Review an existing deployment, design a new agent, or implement the controls identified in an assessment."/><TextLink href="/services">All services</TextLink></div><p className="explorer-instruction">Choose an engagement to see the work and deliverables. Hover, tap, or use the arrow keys.</p><ServiceExplorer/></Container></Section>
<EngagementFinder/>
<Section className="muted-section"><Container><div className="feature-grid"><div><Eyebrow>Agent governance + authorization</Eyebrow><h2>Every agent needs<br/>a defined authority.</h2><p>Set the owner, identity, permitted actions, resource boundaries, and review gates before expanding autonomy.</p><TextLink href="/agent-governance">See the authorization path</TextLink></div><div className="control-questions">{["Who owns this agent?","Which identity does it use?","What can it read or change?","What requires approval?","How is access reviewed and retired?"].map((q,i)=><p key={q}><span>0{i+1}</span>{q}</p>)}</div></div></Container></Section>
<Section><Container><div className="feature-grid"><div><Eyebrow>Microsoft AI specialization</Eyebrow><h2>Deploy Microsoft AI.<br/>Define who can access what.</h2><p>Prepare Microsoft 365 Copilot and Copilot Studio deployments by reviewing source permissions, agent actions, and environment controls. Connect Entra identity and Purview data protection to the workload in scope.</p><TextLink href="/microsoft-ai">Microsoft AI Governance</TextLink></div><div className="technology-grid">{[["Microsoft 365 Copilot","Source access + deployment readiness"],["Copilot Studio","Agents + environment controls"],["Microsoft Entra","Identity + authorization"],["Microsoft Purview","Data protection + evidence"],["Microsoft Foundry","Model + agent architecture"],["Power Platform","Workflow + integration boundaries"]].map(([t,d])=><div key={t}><strong>{t}</strong><p>{d}</p></div>)}</div></div></Container></Section>
<Section className="muted-section"><Container><div className="feature-grid"><div><Eyebrow>Integration + modernization</Eyebrow><h2>Connect AI to your<br/>existing applications.</h2><p>Connect agents to legacy applications through APIs and controlled data access. Define permissions, approval steps, and failure handling before allowing an agent to read or change business records.</p><TextLink href="/services/ai-integration-modernization">Explore modernization</TextLink></div><ModernizationFlow/></div></Container></Section>
<Section><Container><SectionHeading label="How we work" title="Close to your systems. Clear about the next step."/><ol className="process-grid">{[["Understand","Map systems, data, identities, constraints, and purpose."],["Design","Define architecture, permissions, boundaries, and ownership."],["Implement","Build the integrations and controls in an agreed scope."],["Operate","Verify behavior, hand over evidence, and establish reviews."]].map(([t,d],i)=><li key={t}><span className="card-number">0{i+1}</span><h3>{t}</h3><p>{d}</p></li>)}</ol><TextLink href="/how-we-work">Our delivery approach</TextLink></Container></Section>
<Section className="platform-section"><Container><div className="section-heading-row"><SectionHeading label="Engineering in practice" title="Close to the realities of production." text="Selected platform engineering and technical operations on independent digital properties."/><TextLink href="/services/platform-engineering">Platform engineering</TextLink></div><div className="platform-grid"><article><span className="eyebrow">Research platform</span><h3>sougataroy.com<span className="sr-only">Independent research property</span></h3><p>Next.js development, content infrastructure, hosting and domain administration, deployment, and ongoing technical operations.</p></article><article><span className="eyebrow">Digital media + resources</span><h3>Voyagers Beyond</h3><p>Platform engineering, content infrastructure, deployment, maintenance, and automation.</p></article></div><p className="small-note">Content and editorial rights remain with the respective property owners. These references describe technical work, not paid-client or endorsement claims.</p></Container></Section>
<Section><Container><div className="section-heading-row"><SectionHeading label="Insights" title="The decisions beneath the technology."/><TextLink href="/insights">All insights</TextLink></div><div className="insight-grid">{insights.map(item=><InsightCard key={item.slug} item={item}/>)}</div></Container></Section><CTASection/></>;}


